apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "navigator.fullname" . }}-sandbox
  labels:
    {{- include "navigator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "navigator.fullname" . }}-sandbox
subjects:
  - kind: ServiceAccount
    name: {{ include "navigator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
